/**
 * KURA Notes - Content Models
 *
 * TypeScript interfaces and types for content entities
 */

/**
 * Content types supported by the system
 */
export type ContentType = 'text' | 'image' | 'pdf' | 'audio';

/**
 * Content source/origin
 */
export type ContentSource = 'ios-shortcut' | 'web' | 'api' | 'manual';

/**
 * Content entity as stored in the database
 */
export interface Content {
  id: string;
  file_path: string;
  content_type: ContentType;
  title: string | null;
  source: ContentSource | null;
  tags: string[]; // Stored as JSON in DB
  annotation: string | null;
  extracted_text: string | null;
  created_at: string; // ISO 8601 datetime string
  updated_at: string; // ISO 8601 datetime string
}

/**
 * Raw content row as returned from SQLite
 * (tags are stored as JSON string in the database)
 */
export interface ContentRow {
  id: string;
  file_path: string;
  content_type: ContentType;
  title: string | null;
  source: ContentSource | null;
  tags: string | null; // JSON string
  annotation: string | null;
  extracted_text: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Input for creating new content
 */
export interface CreateContentInput {
  id: string; // UUID generated by caller
  file_path: string;
  content_type: ContentType;
  title?: string;
  source?: ContentSource;
  tags?: string[];
  annotation?: string;
  extracted_text?: string;
}

/**
 * Input for updating existing content
 */
export interface UpdateContentInput {
  title?: string;
  tags?: string[];
  annotation?: string;
  extracted_text?: string;
}

/**
 * Search result with metadata
 */
export interface ContentSearchResult {
  id: string;
  title: string | null;
  excerpt: string; // Snippet from matched content
  content_type: ContentType;
  relevance_score: number; // 0-1 for vector search
  tags: string[];
  created_at: string;
}

/**
 * Full-text search filters
 */
export interface SearchFilters {
  contentTypes?: ContentType[];
  tags?: string[];
  dateFrom?: string; // ISO 8601
  dateTo?: string; // ISO 8601
  source?: ContentSource;
}

/**
 * Search history entry
 */
export interface SearchHistory {
  id: number;
  query: string;
  results_count: number;
  created_at: string;
}

/**
 * Database schema version
 */
export interface SchemaVersion {
  version: number;
  applied_at: string;
  description: string;
}
