/**
 * KURA Notes - Content Models
 *
 * TypeScript interfaces and types for content entities
 */

/**
 * Content types supported by the system
 */
export type ContentType = 'text' | 'image' | 'pdf' | 'audio';

/**
 * Content source/origin
 */
export type ContentSource = 'ios-shortcut' | 'web' | 'api' | 'manual';

/**
 * Embedding generation status
 */
export type EmbeddingStatus = 'pending' | 'completed' | 'failed';

/**
 * Image metadata stored as JSON in database
 */
export interface ImageMetadata {
  width: number;
  height: number;
  format: string; // 'jpeg', 'png', 'webp', etc.
  size: number; // File size in bytes
}

/**
 * PDF metadata stored as JSON in database
 */
export interface PdfMetadata {
  filename: string; // Original filename
  size: number; // File size in bytes
  pageCount?: number; // Number of pages (if available)
}

/**
 * Content entity as stored in the database
 */
export interface Content {
  id: string;
  file_path: string;
  content_type: ContentType;
  title: string | null;
  source: ContentSource | null;
  tags: string[]; // Stored as JSON in DB
  annotation: string | null;
  extracted_text: string | null;
  embedding_status: EmbeddingStatus;
  thumbnail_path: string | null; // Path to generated thumbnail (for images)
  image_metadata: ImageMetadata | null; // Image metadata (dimensions, format, size)
  pdf_metadata: PdfMetadata | null; // PDF metadata (filename, size, page count)
  created_at: string; // ISO 8601 datetime string
  updated_at: string; // ISO 8601 datetime string
}

/**
 * Raw content row as returned from SQLite
 * (tags and image_metadata are stored as JSON strings in the database)
 */
export interface ContentRow {
  id: string;
  file_path: string;
  content_type: ContentType;
  title: string | null;
  source: ContentSource | null;
  tags: string | null; // JSON string
  annotation: string | null;
  extracted_text: string | null;
  embedding_status: EmbeddingStatus;
  thumbnail_path: string | null;
  image_metadata: string | null; // JSON string
  pdf_metadata: string | null; // JSON string
  created_at: string;
  updated_at: string;
}

/**
 * Input for creating new content
 */
export interface CreateContentInput {
  id: string; // UUID generated by caller
  file_path: string;
  content_type: ContentType;
  title?: string;
  source?: ContentSource;
  tags?: string[];
  annotation?: string;
  extracted_text?: string;
}

/**
 * Input for updating existing content
 */
export interface UpdateContentInput {
  title?: string;
  tags?: string[];
  annotation?: string;
  extracted_text?: string;
  embedding_status?: EmbeddingStatus;
  thumbnail_path?: string;
  image_metadata?: ImageMetadata;
  pdf_metadata?: PdfMetadata;
}

/**
 * Search result with metadata
 */
export interface ContentSearchResult {
  id: string;
  title: string | null;
  excerpt: string; // Snippet from matched content
  content_type: ContentType;
  relevance_score: number; // 0-1 for vector search
  tags: string[];
  created_at: string;
}

/**
 * Full-text search filters
 */
export interface SearchFilters {
  contentTypes?: ContentType[];
  tags?: string[];
  dateFrom?: string; // ISO 8601
  dateTo?: string; // ISO 8601
  source?: ContentSource;
}

/**
 * Search history entry
 */
export interface SearchHistory {
  id: number;
  query: string;
  results_count: number;
  created_at: string;
}

/**
 * Database schema version
 */
export interface SchemaVersion {
  version: number;
  applied_at: string;
  description: string;
}
